name: Tests
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
          cd test
          ../bin/agfusion download -g hg19
          ../bin/agfusion download -s homo_sapiens -r 95
          ../bin/agfusion download -s mus_musculus -r 84
          pyensembl install --release 84 --species mus_musculus
          pyensembl install --release 75 --species homo_sapiens
          pyensembl install --release 95 --species homo_sapiens
      - name: Test with pytest
        run: |
          cd test
          pytest
      - name: Test build bundle for pip
        run: |
          pip install setuptools wheel build
          python setup.py sdist bdist_wheel
